// DOM-independent regression checks. These do not replace real Safari layout testing.
const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
const handlers={},nodes={};
const node=selector=>nodes[selector]??={innerHTML:'',textContent:'',style:{},open:false,close(){this.open=false;},showModal(){this.open=true;}};
const context=vm.createContext({console,Intl,Date,Set,Map,URL,Uint8Array,JSON,Math,Number,String,Promise,Error,TypeError,performance:{getEntriesByType:()=>[]},crypto:require('node:crypto').webcrypto,sessionStorage:{getItem:()=>null,removeItem(){},setItem(){}},document:{querySelector:node,body:{setAttribute(){},removeAttribute(){}},addEventListener:(type,fn)=>(handlers[type]??=[]).push(fn)},setTimeout:()=>0,setInterval:()=>0,fetch:()=>{throw Error('unexpected request')}});
vm.runInContext(fs.readFileSync(path.join(root,'site/catalog.js'),'utf8'),context);
let source=fs.readFileSync(path.join(root,'site/app.js'),'utf8').replace(/start\(\);\s*$/,'');vm.runInContext(source,context);
const run=js=>vm.runInContext(js,context);
let count=0;function check(label,fn){fn();console.log('PASS',label);count++;}
check('five snack types and a single stationery choice',()=>{assert.equal(run("PRODUCT_CATALOG.filter(p=>p.category==='간식').length"),5);assert.equal(run("PRODUCT_CATALOG.filter(p=>p.category==='문구').length"),1)});
check('all catalogue images point to bundled files',()=>{for(const p of JSON.parse(run('JSON.stringify(PRODUCT_CATALOG)'))){if(p.src)assert(fs.existsSync(path.join(root,'site',p.src)));assert(!run(`productArt(${p.id})`).includes('undefined'));}});
check('old stationery choices resolve to the one new illustration',()=>{for(const id of [0,1,2,4,5])assert(run(`productArt(${id})`).includes('./assets/shop/stationery.png'))});
run(`state={actor:'teacher',me:{lumen:200},students:[],products:[{id:'a',name:'마이쮸',image:8,price:0,stock:0,active:false},{id:'b',name:'문구',image:0,category:'문구',price:100,stock:2,active:true}],discounts:{},serverTime:Date.now(),threads:[]};`);
check('students cannot see unlisted starter snacks',()=>{run("state.actor='student';shopCategory='전체'");const html=run('shopPage()');assert(!html.includes('<h3>마이쮸</h3>'));assert(html.includes('<h3>문구</h3>'))});
check('category filters the shop',()=>{run("state.actor='teacher';shopCategory='간식'");let html=run('shopPage()');assert(html.includes('<h3>마이쮸</h3>'));assert(!html.includes('<h3>문구</h3>'))});
check('reply text survives render and is HTML escaped',()=>{run(`selectedThread='thread1';replyDrafts.thread1='<내 답장>';state.threads=[{id:'thread1',title:'문의',student:'student',closed:false,lastBy:'student',messages:[{body:'안녕',by:'student',time:Date.now()}]}]`);assert(run('messagesPage()').includes('&lt;내 답장&gt;'))});
check('product picker has visual radio choices',()=>{const html=run('productPicker(10)');assert.equal((html.match(/type="radio"/g)||[]).length,run('PRODUCT_CATALOG.length'));assert(html.includes('value="10" checked'))});
run(`state={actor:'teacher',students:[{id:'p1',number:1,login:'S01',name:'도희',active:true,character:'1-0',lumen:200,xp:120},{id:'p2',number:2,login:'S02',name:'로아',active:true,character:'1-1',lumen:100,xp:150}],jobs:[{id:'merchant',name:'상인',active:true,reward:[20,10]}],donations:[{id:'d1',student:'p1',round:'round',amount:50,date:'2026-10-04',time:100000},{id:'d2',student:'p1',round:'round',amount:30,date:'2026-10-04'},{id:'d3',student:'p2',round:'old',amount:90,date:'2026-10-03'}],thermo:{round:'round'},serverTime:Date.now()};selected=new Set(['p1']);`);
check('point cards show character, lumen, XP and selection separately',()=>{const html=run('selector()');assert(html.includes('200 루멘'));assert(html.includes('120 XP'));assert(html.includes('aria-pressed="true"'));assert.equal((html.match(/class="creature /g)||[]).length,2)});
check('activity status uses recorded students independently from selection',()=>{const html=run("selector(new Set(['p2']))");assert.equal((html.match(/avatar inactive/g)||[]).length,1);assert.equal((html.match(/activity-status done/g)||[]).length,1);assert(html.includes('미완료'));assert(html.includes('완료 ✓'))});
check('donation history totals the current round and supports old dates',()=>{const html=run('donationHistory()');assert(html.includes('80 루멘'));assert(!html.includes('90 루멘'));assert(html.includes('시각 기록 없음'));assert(html.includes('도희'))});
check('job drag/tap state supports sharing, moving and unassignment',()=>{run("jobDraft={};jobPicked='p1';placeJob('merchant');jobPicked='p2';placeJob('merchant')");assert.deepEqual(JSON.parse(run('JSON.stringify(jobDraft)')),{p1:'merchant',p2:'merchant'});run("jobPicked='p1';placeJob('')");assert.deepEqual(JSON.parse(run('JSON.stringify(jobDraft)')),{p2:'merchant'});const html=run('jobBoard()');assert(html.includes('draggable="true"'));assert(html.includes('name="p2" value="merchant"'));run("placeJob('unknown','p1')");assert.equal(run('jobDraft.p1'),undefined)});
check('quest and thematic decoration assets are bundled',()=>{for(const menu of ['reading','bank','shop','messages','quests','jobs','activities','points','thermo']){run(`page='${menu}'`);const html=run('pageDecor()');assert(html.includes('page-scene'));for(const m of html.matchAll(/src="([^"]+)"/g))assert(fs.existsSync(path.join(root,'site',m[1])))}assert(fs.existsSync(path.join(root,'site/assets/quest-art.webp')))});
(async()=>{run("token='session-a';start=async()=>{};replyDrafts={thread1:'private'};messageDraft={title:'private',body:'private'}");await run('logout(false)');check('logout clears drafts before next user',()=>{assert.equal(run('Object.keys(replyDrafts).length'),0);assert.equal(run('messageDraft.body'),'');assert.equal(run('token'),null)});console.log(`${count} UI logic checks passed`);})().catch(e=>{console.error(e);process.exitCode=1});
// Run management checks in the existing GitHub Actions web verification step.
require('./test_management_ui.cjs');
